### ISSUE TITLE
list visual

### ISSUE THREAD

**Issue by luhem** [jongio/PowerBI-visuals-radioSlicer#1]
Currently the radio slicer displays list of values horizontally.  Is there a setting to display the value as a list vertically?

**Comment by jongio** [comment]
@luhem - I added "Vertical" support.

https://github.com/jonbgallant/PowerBI-visuals-radioSlicer/raw/master/radioSlicer/dist/radioSlicer.pbiviz

You can find the toggle in the Format->General tab

![image](https://user-images.githubusercontent.com/2163001/43108108-107d6fe0-8e95-11e8-9702-cad0d0e6a52a.png)

![image](https://user-images.githubusercontent.com/2163001/43108122-1d851e86-8e95-11e8-83ad-d47ac4174b5a.png)

Let me know if you run into any issues.
