### ISSUE TITLE
Similar slider using checkboxes

### ISSUE THREAD

**Issue by pramodx** [jongio/PowerBI-visuals-radioSlicer#3]
I have been trying to implement your solution for a task I have which involves using checkboxes instead of radio buttons. My data is also tabular with 3 columns. Everything seems to be in order till I hit hte createSelectionIds method where the code breaks.

Could you extend this to include checkboxes as well and how would the selection work?

Thanks,

**Comment by jongio** [comment]
If you send me your email and a link to the code here: https://jong.io/contact, then I can connect you with the PBI visual support team.
